meta:
  Description: Initial Default Content
  Name: DefaultStore
  Type: default
  Version: 0.0.0
sections:
  templates:
    usrshare:
      Contents: |
        usrshare
      Description: A test template for DefaultStore testing
      ID: usrshare
